name: Deployment

on:
  workflow_dispatch:

env: 
  HOST: cassini.cs.kent.edu
  USER: test123
  TARGET: test123@cassini.cs.kent.edu
  RUN: ssh -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no test123@cassini.cs.kent.edu
  COPY: scp -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no

jobs:
  deployment:
    name: Deploy Software
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ID_ED25519 }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Examine Server Environment
        run: | 
          echo $ $RUN hostname
          $RUN hostname 
          echo $ $RUN pwd
          $RUN pwd
          echo $ $RUN ls -la 
          $RUN ls -la 

      - name: Deploy the hello page
        run: |
          $COPY index.html $TARGET:. 